---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapi
  template:
    metadata:
      labels:
        app: todoapi
    spec:
      containers:
      - name: todoapi
        image: jpetersenames/todoapi
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: todoapi
spec:
  type: ClusterIP
  ports:
  - port: 9000
  selector:
    app: todoapi
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: todoapi
  labels:
    app: todoapi
    component: ingress
spec:
  rules:
    - host: todoapi.k3d.localhost
      http:
        paths:
          - path: /
            backend:
              serviceName: todoapi
              servicePort: 9000
  tls:
    - hosts:
      - todoapi.k3d.localhost
