apiVersion: database.example.org/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: database
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  parameters:
    storageGB: 20
  compositionSelector:
    matchLabels:
      provider: aws
  writeConnectionSecretToRef:
    name: db-conn
