apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  project: infra
  source:
    path: cluster/charts/crossplane
    repoURL: https://github.com/crossplane/crossplane
    targetRevision: v1.3.0
    helm:
      releaseName: crossplane-system
      version: v3
      valueFiles:
      - values.yaml.tmpl
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true

