apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: root
  project: default
  source:
    path: apps
    repoURL: https://github.com/found-it/argocd-quickstart
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
