apiVersion: v1
kind: Namespace
metadata:
  name: root
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: root
  project: {{ .Values.spec.project }}
  source:
    path: apps
    repoURL: https://github.com/found-it/argocd-quickstart
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
