apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo
  namespace: todo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: todo
  project: default
  source:
    repoURL: https://github.com/found-it/todoapi.git
    targetRevision: HEAD
    path: manifests
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
